<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEFW8QPz\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEFW8QPz/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerEFW8QPz.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerEFW8QPz\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerEFW8QPz\appAppKernelProdContainer([
    'container.build_hash' => 'EFW8QPz',
    'container.build_id' => '3b447cf8',
    'container.build_time' => 1708976223,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEFW8QPz');
