version: '3'
services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
  prestashop:
    container_name: prestashop
    image: immrung/prestashop-1.7.8-build:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_FOLDER_ADMIN: admin4577
      PS_FOLDER_INSTALL: install4577
    networks:
      - prestashop_network
    volumes:
      - ./img:/var/www/html/img
      - ./themes:/var/www/html/themes
      - ./modules:/var/www/html/modules
      - ./controllers:/var/www/html/controllers
      - ./classes:/var/www/html/classes
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - prestashop_network
networks:
  prestashop_network:
volumes:
  dbdata: